### ISSUE TITLE
Encoding::UndefinedConversionError [ruby 2.3.0]

### ISSUE THREAD

**Issue by elsom25** [tilfin/ougai#11]
When attempting to use, I get:

```rb
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'ougai'
=> true
irb(main):003:0> logger = Ougai::Logger.new(STDOUT)
=> #<Ougai::Logger:0x007fa34e1a76a8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007fa34e1a7630 @datetime_format=nil>, @formatter=#<Ougai::Formatters::Bunyan:0x007fa34e1a7540 @app_name="irb", @hostname="Jesse\xE2\x80\x99s-MacBook-Pro", @trace_indent=2, @trace_max_lines=100>, @logdev=#<Logger::LogDevice:0x007fa34e1a75e0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007fa34e1a7590>>, @default_message="No message", @exc_key=:err>
irb(main):005:0> logger.info('Information!')
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `encode'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	from /Users/jessemcginnis/.gem/ruby/2.3.3/gems/ougai-0.7.3/lib/ougai/formatters/bunyan.rb:8:in `call'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:546:in `format_message'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:434:in `add'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:489:in `info'
	from /Users/jessemcginnis/.gem/ruby/2.3.3/gems/ougai-0.7.3/lib/ougai/logger.rb:20:in `info'
	from (irb):5
	from /opt/rubies/2.3.3/bin/irb:11:in `<main>'
```

**Comment by tilfin** [comment]
@elsom25  Firstly, Thanks your trying Ougai!

I guess your irb's encoding is not UTF-8 so that JSON generater failed to read your hostname that contains UTF-8 character.

Please try to run `$ irb -E 'UTF-8'`

**Comment by elsom25** [comment]
sadly didn't seem to help!

```rb
➔ irb -E 'UTF-8'
irb(main):001:0> require 'rubygems'
=> false
irb(main):002:0> require 'ougai'
=> true
irb(main):003:0> logger = Ougai::Logger.new(STDOUT)
=> #<Ougai::Logger:0x007ffc271a79f0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x007ffc271a7950 @datetime_format=nil>, @formatter=#<Ougai::Formatters::Bunyan:0x007ffc271a7860 @app_name="irb", @hostname="Jesse\xE2\x80\x99s-MacBook-Pro", @trace_indent=2, @trace_max_lines=100>, @logdev=#<Logger::LogDevice:0x007ffc271a7900 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x007ffc271a78b0>>, @default_message="No message", @exc_key=:err>
irb(main):004:0> logger.info('Information!')
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `encode'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	from /Users/jessemcginnis/.gem/ruby/2.3.3/gems/ougai-0.7.3/lib/ougai/formatters/bunyan.rb:8:in `call'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:546:in `format_message'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:434:in `add'
	from /opt/rubies/2.3.3/lib/ruby/2.3.0/logger.rb:489:in `info'
	from /Users/jessemcginnis/.gem/ruby/2.3.3/gems/ougai-0.7.3/lib/ougai/logger.rb:20:in `info'
	from (irb):4
	from /opt/rubies/2.3.3/bin/irb:11:in `<main>'
```

**Comment by tilfin** [comment]
@elsom25 Please avoid the problem for now.
```
irb(main):005:0> require 'rubygems'
irb(main):006:0> require 'ougai'
irb(main):007:0> logger = Ougai::Logger.new(STDOUT)
irb(main):009:0> logger.formatter = Ougai::Formatters::Bunyan.new('myapp', 'myhost')
irb(main):010:0> logger.info('Information')
{"name":"myapp","hostname":"myhost","pid":21919,"level":30,"time":"2017-01-21T02:28:11.438+09:00","v":0,"msg":"Information"}
```
specifying 'myhost' instead of getting your hostname

**Comment by elsom25** [comment]
Thanks! For now this works to get around the issue

**Comment by tilfin** [comment]
It was due that Socket.gethostname always returns an ASCII-8BIT encoding string.
